<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="NiceViewWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/NiceViewWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/NiceViewWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://NiceView">
    <import location="NiceView/NiceView.wsdl" namespace="http://NiceView"/>
    <plnk:partnerLinkType name="NiceViewLinkType">
        <plnk:role name="NiceViewRole" portType="ns:NiceViewPortType"/>
    </plnk:partnerLinkType>
</definitions>
